routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    $data['title'] = "Login ";
    return view('auth.login', $data);
})->middleware('guest');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('car', 'CarController')->middleware('auth');

Route::resource('brand', 'BrandController')->middleware('auth');

Route::resource('employee', 'EmployeeController')->middleware('auth');

Route::resource('client', 'ClientController')->middleware('auth');

Route::get('booking', ['as' => 'booking.index', 'uses' => 'BookingController@index' ])->middleware('auth');

Route::get('list-member', 'BookingController@listMember' )->middleware('auth');

Route::post('create-client', ['as' => 'create-client', 'uses' => 'BookingController@createClient' ])->middleware('auth');

Route::post('booking/details', ['as' => 'booking.calculate', 'uses' => 'BookingController@calculate'])->middleware('auth');

Route::post('booking/process', ['as' => 'booking.process', 'uses' => 'BookingController@process'])->middleware('auth');

Route::get('returns', ['as' => 'returns.index', 'uses' => 'ReturnController@index' ])->middleware('auth');

Route::get('returns/information', ['as' => 'returns.information', 'uses' => 'ReturnController@information'])->middleware('auth');

Route::post('returns/process', ['as' => 'returns.process', 'uses' => 'ReturnController@process'])->middleware('auth');

Route::get('reports/transaction', 'ReportController@index')->middleware('auth');

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ $title }} - Rentcar</title>

    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="{{ asset('dist/css/adminlte.min.css') }}">
    <!-- iCheck -->
    <link rel="stylesheet" href="{{ asset('plugins/iCheck/all.css')}}">
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
    <!-- DataTables -->
    <link rel="stylesheet" href="{{ asset('plugins/datatables/dataTables.bootstrap4.css')}}">
    <!-- datepicker -->
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">

    <link rel="stylesheet" href="{{ asset('style.css')}}">

    <link rel="icon" href="{{ asset('dist/img/AdminLTELogo.png')}}">
</head>
<body class="hold-transition sidebar-mini">
    <div class="wrapper" >
        @guest
            @yield('login')
        @else
            @include('layouts.navbar')
            @include('layouts.sidebar')
            <div class="content-wrapper">
                
                <section class="content-header">
                    <div class="container-fluid">
                        <div class="row mb-2">
                            <div class="col-sm-6">
                                <h1>{{ $title }}</h1>
                            </div>
                        </div>
                        <!-- flashmessage -->
                        @include('layouts.flash-message')

                    </div>
                </section>
                @yield('content')
            </div>

            @include('layouts.footer')
        @endguest
    
    </div>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}"></script>
    
    <!-- jQuery -->
    <script src=" {{ asset('plugins/jquery/jquery.min.js') }}"></script>
    <!-- Datepicker -->
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script>
    $( function(){
        $( "#datepicker" ).datepicker({ dateFormat: 'yy-mm-dd', changeYear: true,
        changeMonth: true, yearRange: '1945:'+(new Date).getFullYear() });
        $( "#datepickers" ).datepicker({ dateFormat: 'yy-mm-dd', changeYear: true,
        changeMonth: true, yearRange: '1945:'+(new Date).getFullYear() });
        });
    </script>

    <!-- Bootstrap 4 -->
    <script src="{{ asset('plugins/bootstrap/js/bootstrap.bundle.min.js') }}"></script>

    <!-- AdminLTE App -->
    <script src="{{ asset('dist/js/adminlte.min.js') }}"></script>
    <!-- DataTables -->
    <script src="{{ asset('plugins/datatables/jquery.dataTables.js') }}"></script>
    <script src="{{ asset('plugins/datatables/dataTables.bootstrap4.js') }}"></script>
    <!-- cleave js -->
    <script src="{{ asset('cleave-js/dist/cleave.min.js') }}"></script>
    <!-- CHECKBOX -->
    <script src="{{ asset('plugins/iCheck/icheck.min.js') }}"></script>

    <script>
    $(function () {
        $("#myTable").DataTable();
    });
   
    </script>

    @stack('scripts')
          
</body>
</html>

resources/views/layouts/flash-message.blade.php
@if (Session::get('success'))
    <div class="alert alert-success alert-block">
        <button type="button" class="close" data-dismiss="alert">×</button>	
        {{ Session::get('success') }}
    </div>
@endif

@if (Session::get('danger'))
    <div class="alert alert-danger alert-block">
        <button type="button" class="close" data-dismiss="alert">×</button>	
        {{ Session::get('danger') }}
    </div>
@endif

@if (Session::get('warning'))
    <div class="alert alert-warning alert-block">
        <button type="button" class="close" data-dismiss="alert">×</button>	
        {{ Session::get('warning') }}
    </div>
@endif

resources/views/layouts/footer.blade.php
<footer class="main-footer">
        <div class="float-right d-none d-sm-block">
          <b>Selamat Datang</b> | Di Website Rental Mobil
        </div>
        <strong>Copyright &copy; 2020 <a href="#">BUDAy</a>.</strong> All rights
        reserved.
</footer>

resources/views/layouts/navbar.blade.php
<nav class="main-header navbar navbar-expand bg-white navbar-light border-bottom">
<!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
        <!-- Messages Dropdown Menu -->
        <li class="nav-item dropdown">
            <a class="nav-link" href="{{ route('logout') }}"
                onclick="event.preventDefault();
                            document.getElementById('logout-form').submit();">
                <i class="fa fa-sign-out"></i> Logout
                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                        {{ csrf_field() }}
                </form>
            </a>
        </li>
    </ul>
</nav>

resources/views/layouts/sidebar.blade.php
<!-- Main Sidebar Container -->
<aside class="main-sidebar sidebar-dark-primary elevation-4">
        <!-- Brand Logo -->
    <a href="{{ route('home') }}" class="brand-link">
        <img src="{{asset('dist/img/AdminLTELogo.png')}}"
            alt="AdminLTE Logo"
            class="brand-image img-circle elevation-3"
            style="opacity: .8">
        <span class="brand-text font-weight-light">Sistem Rental Mobil</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
        <!-- Sidebar user (optional) -->
        <div class="user-panel mt-3 pb-3 mb-3 d-flex">
            <div class="image">
                <img src="{{ asset('dist/img/avatar5.png')}}" class="img-circle elevation-2" alt="User Image">
            </div>
            <div class="info">
                <a href="#" class="d-block">{{ Auth::user()->email }}</a>
            </div>
        </div>

        <!-- Sidebar Menu -->
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                <!-- Add icons to the links using the .nav-icon class
                    with font-awesome or any other icon font library -->
                <li class="nav-item has-treeview menu-open">
                    <a href="#" class="nav-link ">
                        <i class="nav-icon fa fa-circle-o"></i>
                        <p>
                        MASTER
                        <i class="right fa fa-angle-left"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a href=" {{ route('car.index') }} " class="nav-link {{($menu==1 ? 'active' : '')}}">
                                <i class="fa fa-car nav-icon"></i>
                                <p>Data Mobil</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href=" {{ route('brand.index') }} " class="nav-link {{($menu==2 ? 'active' : '')}}">
                                <i class="fa fa-database nav-icon"></i>
                                <p>Data Brands</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href=" {{ route('employee.index') }} " class="nav-link {{($menu==3 ? 'active' : '')}}">
                                <i class="fa fa-user nav-icon"></i>
                                <p>Data User</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href=" {{ route('client.index') }} " class="nav-link {{($menu==4 ? 'active' : '')}}">
                                <i class="fa fa-users nav-icon"></i>
                                <p>Data Pelanggan</p>
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="nav-item has-treeview menu-open">
                        <a href="#" class="nav-link ">
                            <i class="nav-icon fa fa-circle-o"></i>
                            <p>
                            Transaksi
                            <i class="right fa fa-angle-left"></i>
                            </p>
                        </a>
                        <ul class="nav nav-treeview">
                            <li class="nav-item">
                                <a href=" {{ route('booking.index') }} " class="nav-link {{($menu==5 ? 'active' : '')}}">
                                    <i class="fa fa-book nav-icon"></i>
                                    <p>Pesan</p>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href=" {{ route('returns.index') }} " class="nav-link {{($menu==6 ? 'active' : '')}}">
                                    <i class="fa fa-dollar nav-icon"></i>
                                    <p>Kembali</p>
                                </a>
                            </li>
                        </ul>
                </li>
                <li class="nav-item has-treeview menu-open">
                        <a href="#" class="nav-link ">
                            <i class="nav-icon fa fa-circle-o"></i>
                            <p>
                            Laporan
                            <i class="right fa fa-angle-left"></i>
                            </p>
                        </a>
                        <ul class="nav nav-treeview">
                            <li class="nav-item">
                                <a href=" {{ url('reports/transaction') }} " class="nav-link {{($menu==7 ? 'active' : '')}}">
                                    <i class="fa fa-book nav-icon"></i>
                                    <p>Transaksi</p>
                                </a>
                            </li>
                        </ul>
                </li>
            </ul>
        </nav>
        <!-- /.sidebar-menu -->
    </div>
        <!-- /.sidebar -->
</aside>